Parameters:
  DDBArn:
    Default: arn:aws:dynamodb:ap-southeast-1:494526681395:table/sunjing
    Type: String
Resources:
  MyLambda:
    Properties:
      Code:
        S3Bucket: sunjing-lambda-code
        S3Key: b2ccd2e2a1ce727dc821032662922cc2
      Environment:
        Variables:
          REGION:
            Ref: AWS::Region
          TABLE_NAME: sunjing
      Handler: index.handler
      Role:
        Fn::GetAtt:
        - MyLambdaExecutionRole
        - Arn
      Runtime: nodejs12.x
      Timeout: 900
    Type: AWS::Lambda::Function
  MyLambdaExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: 2012-10-17
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource:
            - arn:aws:logs:*:*:log-group:/aws/lambda/*:*
          Version: 2012-10-17
        PolicyName: sunjing-lambda-policy-log
      - PolicyDocument:
          Statement:
          - Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            Effect: Allow
            Resource:
            - Ref: DDBArn
          Version: 2012-10-17
        PolicyName: sunjing-lambda-policy-ddb
    Type: AWS::IAM::Role
