#!/bin/bash

TABLE_NAME=sunjing
BACKUP_TABLE_NAME=sunjing_backup
HASH_KEY=projectName
RANGE_KEY=projectType
ATTRIBUTES_MEMBER_NAME=memberName
ATTRIBUTES_START_DATE=startDate
INDEX_NAME=memberNameIndex
